import csv

def generate_data():
    # 70 Contoh kalimat positif
    positif = [
        "Sangat senang naik KRL sekarang, bersih, sejuk, dan aman sekali.",
        "Terima kasih KAI, pelayanan gerbong khusus wanita sangat tertib dan nyaman.",
        "Pembangunan IKN Nusantara berjalan sangat lancar dan memberikan harapan pemerataan.",
        "Fasilitas stasiun Manggarai sekarang sudah jauh lebih baik dan tertata rapi.",
        "Naik Transjakarta hari ini sangat lancar, bus bersih dan sopir mengemudi dengan aman.",
        "Apresiasi setinggi-tingginya untuk petugas MRT Jakarta yang selalu ramah membantu penumpang.",
        "Layanan LRT Jabodebek cepat sekali, waktu tempuh memangkas kemacetan secara signifikan.",
        "Integrasi tarif antar-moda transportasi di Jakarta sangat memudahkan dan menghemat biaya.",
        "IKN Nusantara akan menjadi simbol kemajuan teknologi dan keramahan lingkungan Indonesia.",
        "Sangat nyaman menggunakan Commuter Line di akhir pekan bersama keluarga.",
        "Petugas keamanan di KRL sangat responsif dan sigap menjaga kenyamanan penumpang.",
        "Proyek MRT fase baru berjalan tepat waktu, sangat tidak sabar menantikannya selesai.",
        "Penggunaan sistem pembayaran non-tunai di halte Transjakarta sangat praktis dan cepat.",
        "Bus listrik Transjakarta sangat ramah lingkungan dan getarannya sangat halus.",
        "Jalur sepeda di Jakarta sudah mulai rapi dan aman digunakan oleh warga.",
        "Pembangunan infrastruktur jalan tol di luar Jawa mempermudah distribusi barang.",
        "Stasiun KRL kini dilengkapi lift dan eskalator yang sangat ramah disabilitas.",
        "Desain arsitektur stasiun kereta cepat sangat megah, modern, dan membanggakan.",
        "Sistem pendingin udara di gerbong kereta bekerja dengan sangat baik dan sejuk.",
        "Aplikasi pemantauan posisi bus Transjakarta sangat akurat dan membantu perencanaan perjalanan.",
        "Sangat puas dengan ketepatan waktu kereta bandara hari ini.",
        "Keamanan di halte Transjakarta sangat terjamin dengan adanya petugas patroli.",
        "Integrasi stasiun KRL dengan stasiun LRT membuat transit menjadi sangat mudah.",
        "Layanan kereta api jarak jauh sekarang sudah setara dengan pelayanan pesawat terbang.",
        "Kebijakan insentif kendaraan listrik sangat bagus untuk mengurangi polusi udara.",
        "Sangat menikmati perjalanan dengan pemandangan indah sepanjang jalur LRT.",
        "Sosialisasi etika berkendara di transportasi umum sangat bagus dan dipatuhi warga.",
        "Pelayanan ruang menyusui di stasiun MRT sangat bersih dan terawat.",
        "Kereta cepat Jakarta-Bandung sangat revolusioner, cepat, dan nyaman sekali.",
        "Area parkir sepeda di stasiun commuter line aman dan tertata dengan baik.",
        "Perpanjangan rute Transjakarta ke wilayah penyangga sangat membantu komuter.",
        "Sistem pencahayaan di stasiun KRL dimalam hari sangat terang dan membuat aman.",
        "Proses pengembalian dana tiket kereta yang batal sangat cepat dan mudah.",
        "Program tarif khusus bagi pelajar dan lansia di Transjakarta sangat membantu masyarakat.",
        "Informasi suara di dalam gerbong KRL sangat jelas dan multibahasa.",
        "Pembangunan trotoar ramah pejalan kaki di pusat kota sangat nyaman untuk berjalan kaki.",
        "Fasilitas pengisian daya baterai gawai di stasiun sangat membantu saat darurat.",
        "Sangat menyukai kebersihan toilet stasiun MRT yang selalu terjaga wangi.",
        "Uji coba rute baru LRT berjalan lancar dan disambut antusias oleh warga sekitar.",
        "Kondisi jalan raya di sekitar IKN sangat mulus dan tertata dengan indah.",
        "Pelatihan pelayanan bagi pengemudi mikrotrans membuat perjalanan semakin ramah.",
        "Informasi rute di halte busway sangat mudah dipahami bahkan untuk pemula.",
        "Pelayanan kereta kesehatan gratis di daerah terpencil sangat membantu masyarakat.",
        "Pemasangan kamera pemantau di setiap gerbong KRL meningkatkan rasa aman warga.",
        "Petugas kebersihan stasiun bekerja tanpa lelah menjaga lingkungan tetap bersih.",
        "Digitalisasi tiket membuat antrean di loket stasiun berkurang drastis.",
        "Program mudik gratis naik kereta api sangat membantu warga yang ingin pulang kampung.",
        "Sistem drainase di sekitar jalur kereta sangat bagus, tidak ada banjir lagi.",
        "Stasiun transit sekarang memiliki banyak pilihan tempat makan yang bersih.",
        "Ketertiban penumpang saat mengantre masuk gerbong KRL patut diacungi jempol.",
        "Jadwal bus listrik sangat konsisten dan membantu mengurangi polusi suara.",
        "Pembangunan jembatan penyeberangan orang yang estetis menambah keindahan kota.",
        "Kereta wisata menawarkan pengalaman perjalanan yang sangat berkesan dan mewah.",
        "Layanan pelanggan KAI di media sosial sangat cepat dalam menjawab keluhan.",
        "Langkah pemerintah memperluas transportasi publik sangat tepat untuk masa depan.",
        "Fasilitas penitipan barang di stasiun besar sangat praktis bagi pelancong.",
        "Ketepatan waktu LRT Jabodebek patut dicontoh oleh moda transportasi lainnya.",
        "Penggunaan panel surya di atap halte busway menunjukkan komitmen hijau yang baik.",
        "Petugas medis di stasiun transit sangat sigap menolong penumpang yang pingsan.",
        "Sangat nyaman berjalan kaki di trotoar sepanjang jalan Sudirman-Thamrin.",
        "Program subsidi tarif komuter sangat meringankan beban pengeluaran bulanan.",
        "Peluncuran gerbong restorasi dengan menu baru membuat perjalanan jarak jauh menyenangkan.",
        "Peta integrasi transportasi yang dipasang di stasiun sangat jelas bagi turis.",
        "Kenyamanan kursi penumpang di gerbong kelas ekonomi kini jauh lebih baik.",
        "Sistem tiket masuk stasiun menggunakan pemindai wajah sangat modern dan cepat.",
        "Pagar pembatas jalur sepeda melindungi pesepeda dari kendaraan bermotor.",
        "Pembangunan pelabuhan baru mempermudah akses transportasi laut antar pulau.",
        "Apresiasi kebijakan zonasi bebas emisi kendaraan di kawasan wisata sejarah.",
        "Ruang tunggu stasiun yang luas membuat penumpang tidak perlu berdesakan.",
        "Sangat bangga melihat produk kereta buatan dalam negeri digunakan secara luas."
    ]
    
    # 70 Contoh kalimat negatif
    negatif = [
        "KRL selalu telat setiap pagi, transit di Manggarai sangat kacau dan berdesakan.",
        "AC di gerbong KRL mati siang ini, panas sekali seperti di dalam oven.",
        "Sangat kecewa dengan Transjakarta, antrean panjang sekali dan bus jarang datang.",
        "IKN Nusantara hanya membuang anggaran negara di saat rakyat sedang kesulitan ekonomi.",
        "Eskalator di stasiun Manggarai rusak lagi, sangat menyusahkan ibu hamil dan lansia.",
        "Pintu otomatis gerbong KRL sering macet, sangat membahayakan keselamatan penumpang.",
        "Aplikasi pemantau Transjakarta sering error, jadwal yang tertera tidak sesuai kenyataan.",
        "Sopir mikrotrans mengemudi dengan ugal-ugalan dan sering berhenti sembarangan.",
        "Fasilitas toilet di stasiun commuter line sangat kotor, bau pesing dan tidak ada air.",
        "Tarif LRT Jabodebek terlalu mahal untuk jarak tempuh yang relatif pendek.",
        "Waktu tunggu bus Transjakarta di halte transit bisa sampai satu jam, sangat melelahkan.",
        "Pembangunan proyek di IKN merusak ekosistem hutan alam setempat.",
        "Banyak copet berkeliaran di gerbong KRL yang padat, keamanan sangat minim.",
        "Sistem pembayaran tap-in sering macet membuat antrean mengular panjang.",
        "Jalur sepeda di jalan raya sering diserobot sepeda motor dan tempat parkir liar.",
        "Sangat kesal dengan penumpukan penumpang di tangga darurat stasiun.",
        "Kurangnya kursi tunggu di halte membuat penumpang harus berdiri lama saat lelah.",
        "Atap stasiun bocor saat hujan deras, membuat peron menjadi sangat licin.",
        "Pelayanan petugas stasiun sangat kasar dan tidak membantu saat ditanya rute alternatif.",
        "Gerbong khusus wanita sering dimasuki penumpang pria tanpa ada teguran dari petugas.",
        "Suara pengeras suara di gerbong sangat cempreng dan memekakkan telinga.",
        "Pembangunan infrastruktur jalan tol merugikan lahan pertanian produktif milik warga.",
        "Jadwal perjalanan malam KRL terlalu sedikit, komuter lembur kesulitan pulang.",
        "Banyak lubang di sepanjang jalan raya menuju stasiun, sangat rawan kecelakaan.",
        "Layanan kompensasi keterlambatan kereta tidak jelas dan berbelit-belit.",
        "Lampu penerangan di sekitar peron stasiun redup, terasa sangat menyeramkan dimalam hari.",
        "Fasilitas ramah disabilitas di halte busway hanya pajangan dan tidak bisa digunakan.",
        "Desain tangga transit stasiun terlalu curam dan melelahkan bagi lansia.",
        "Tiket kereta cepat terlalu mahal, hanya bisa dinikmati golongan masyarakat mampu.",
        "Pelayanan makanan di dalam kereta jarak jauh harganya selangit namun rasanya hambar.",
        "Sistem ventilasi udara di stasiun bawah tanah kurang optimal, terasa pengap sekali.",
        "Antrean pembelian tiket di stasiun commuter line sangat panjang karena mesin tiket rusak.",
        "Pembangunan jalan layang menyebabkan kemacetan parah selama berbulan-bulan tanpa solusi.",
        "Halte busway yang terbakar setahun lalu sampai sekarang belum diperbaiki sepenuhnya.",
        "Jalur khusus busway banyak diserobot kendaraan pribadi, polisi kurang tegas.",
        "Petugas loket tidak ramah dan lambat sekali melayani penukaran kartu yang rusak.",
        "Rencana pemindahan ibu kota ke IKN terkesan sangat terburu-buru dan dipaksakan.",
        "Sangat tidak nyaman dengan bau asap rokok di sekitar area luar stasiun.",
        "Tarif integrasi transportasi umum masih sulit diterapkan secara merata di lapangan.",
        "Sering terjadi gesekan antar penumpang di dalam gerbong KRL karena saling dorong.",
        "Jarak antar kereta (headway) LRT masih terlalu lama, membuat stasiun penuh sesak.",
        "Lift khusus disabilitas sering disalahgunakan oleh penumpang yang berbadan sehat.",
        "Tidak ada informasi pembatalan jadwal kereta yang jelas saat terjadi gangguan listrik.",
        "Ruang menyusui di stasiun terkunci rapat dan petugas tidak tahu kuncinya di mana.",
        "Lantai peron stasiun licin saat hujan, banyak penumpang yang tergelincir.",
        "Pembangunan trotoar baru justru memotong lahan jalan raya dan memperparah macet.",
        "Kualitas bus mikrotrans buruk, banyak yang berkarat dan mesinnya bising.",
        "Kartu berlangganan sering tidak terbaca mesin pembaca kartu, merugikan penumpang.",
        "Keamanan di sekitar stasiun dimalam hari sangat rawan kriminalitas.",
        "Program bus wisata gratis selalu penuh oleh rombongan dan tidak memberi kesempatan warga lain.",
        "Waktu transit antar koridor busway sangat jauh dan harus naik-turun jembatan tinggi.",
        "Penempatan mesin tiket mandiri di stasiun menghalangi alur jalan keluar masuk.",
        "Kebijakan ganjil genap tidak efektif mengurangi macet jika transportasi publik belum memadai.",
        "Petugas keamanan hanya bermain ponsel di pojokan peron saat penumpang berdesakan.",
        "Kursi gerbong ekonomi keras sekali, membuat punggung sakit setelah perjalanan jauh.",
        "Sistem refund tiket kereta online sangat lambat, butuh berhari-hari uang baru kembali.",
        "Suara bising dari konstruksi stasiun baru sangat mengganggu kenyamanan penumpang.",
        "Rute busway sering diubah mendadak tanpa sosialisasi yang cukup ke masyarakat.",
        "Layanan wifi gratis di stasiun tidak pernah bisa tersambung ke internet.",
        "Tarif parkir inap di stasiun besar sangat mahal, membebani pengguna kendaraan pribadi.",
        "Pintu darurat di halte busway sering digembok, membahayakan jika terjadi kebakaran.",
        "Jalur pemandu tunanetra di trotoar terhalang tiang listrik dan pohon.",
        "Kereta jarak jauh sering berhenti lama di tengah jalur tanpa alasan yang jelas.",
        "Kebijakan pembatasan bagasi penumpang kereta terlalu ketat dan merepotkan.",
        "Konstruksi proyek IKN menyebabkan polusi debu yang sangat tebal bagi warga sekitar.",
        "Banyak halte Transjakarta yang berkarat dan plafonnya terancam ambrol.",
        "Kepadatan penumpang KRL di jam sibuk sudah tidak manusiawi lagi.",
        "Sistem deteksi kerusakan rel sangat lambat, sering memicu keterlambatan parah.",
        "Pengumuman gangguan operasional di stasiun hanya menggunakan bahasa daerah setempat.",
        "Waktu integrasi fisik antar stasiun MRT dan KRL memakan waktu jalan kaki terlalu lama."
    ]
    
    # 70 Contoh kalimat netral
    netral = [
        "Hari ini saya bepergian menggunakan KRL Commuter Line tujuan Sudirman.",
        "Pemerintah terus memantau perkembangan fisik pembangunan infrastruktur di IKN.",
        "Jadwal keberangkatan bus Transjakarta dapat diakses melalui aplikasi resmi.",
        "Stasiun Manggarai merupakan stasiun transit terbesar di wilayah Jabodetabek.",
        "Pembangunan MRT Jakarta Fase 2A menghubungkan Bundaran HI hingga Kota.",
        "Tarif perjalanan KRL ditentukan berdasarkan jarak kilometer yang ditempuh.",
        "KRL Commuter Line memiliki gerbong khusus wanita di ujung depan dan belakang.",
        "LRT Jabodebek melayani rute perjalanan dari Jakarta, Bogor, Depok, hingga Bekasi.",
        "Presiden hari ini meninjau lokasi pembangunan kantor kementerian di IKN Nusantara.",
        "Transjakarta mengoperasikan bus berukuran besar, sedang, maupun mikrotrans.",
        "Sistem pembayaran tiket transportasi publik di Jakarta menggunakan kartu uang elektronik.",
        "Gerbang pembayaran otomatis akan terbuka setelah penumpang menempelkan kartu.",
        "Pemerintah DKI Jakarta menambah jumlah armada bus listrik secara bertahap.",
        "Jadwal operasional KRL dimulai pukul empat pagi hingga pukul dua belas malam.",
        "Terdapat beberapa stasiun transit penting di Jakarta seperti Tanah Abang dan Duri.",
        "Pengumuman nama stasiun berikutnya disuarakan di dalam gerbong kereta.",
        "IKN Nusantara terletak di perbatasan Kabupaten Penajam Paser Utara dan Kutai Kartanegara.",
        "Peta jaringan rute KRL terpasang di atas setiap pintu masuk gerbong.",
        "Petugas stasiun rutin memeriksa suhu tubuh penumpang di pintu masuk.",
        "Jumlah penumpang harian commuter line dilaporkan mengalami fluktuasi.",
        "Stasiun MRT bawah tanah dirancang dengan konstruksi tahan gempa bumi.",
        "LRT Jakarta melayani rute pendek dari Pegangsaan Dua menuju Velodrome Rawamangun.",
        "Trotoar di sepanjang jalan Sudirman dirancang dengan lebar sekitar lima meter.",
        "Pemerintah menetapkan aturan kapasitas maksimal isi gerbong selama jam sibuk.",
        "Kereta cepat Jakarta-Bandung melewati beberapa stasiun termasuk stasiun Padalarang.",
        "Pemesanan tiket kereta api jarak jauh dapat dilakukan H-45 sebelum keberangkatan.",
        "Halte Transjakarta Harmoni sedang dalam proses relokasi sementara.",
        "Fasilitas eskalator dan lift stasiun dirawat secara berkala oleh teknisi.",
        "Penggunaan pelindung wajah bagi penumpang tidak lagi diwajibkan oleh regulator.",
        "Rute mikrotrans JakLingko melewati jalan-jalan perumahan penduduk.",
        "Waktu tunggu kedatangan antar busway di halte terpajang di layar informasi elektronik.",
        "Pembagian zonasi kursi penumpang di dalam kereta jarak jauh diatur secara sistematis.",
        "Kementerian Perhubungan melakukan uji kelayakan berkala terhadap bus Transjakarta.",
        "Stasiun Gambir tidak melayani keberangkatan penumpang KRL Commuter Line lagi.",
        "Pembangunan jalan tol Solo-Yogyakarta ditargetkan rampung akhir tahun depan.",
        "Trotoar jalan dipasangi ubin pemandu berwarna kuning untuk penyandang disabilitas.",
        "Layanan kereta bandara melayani rute Manggarai menuju Bandara Soekarno-Hatta.",
        "Pintu gerbong kereta akan terbuka secara otomatis sesampainya di peron stasiun.",
        "Brosur panduan keselamatan perjalanan tersedia di setiap saku kursi kereta.",
        "Tarif parkir sepeda motor di stasiun kereta menggunakan sistem tarif flat.",
        "Sistem informasi stasiun menyiarkan pengumuman kedatangan kereta secara berkala.",
        "Kapasitas daya angkut LRT Jabodebek dirancang untuk menampung ratusan penumpang.",
        "Stasiun Palmerah berada dekat dengan kawasan gedung parlemen DPR RI.",
        "Jalur khusus sepeda ditandai dengan cat berwarna hijau pada permukaan jalan.",
        "Pemerintah daerah mengkaji rencana pembatasan usia operasional bus kota.",
        "Pembangunan halte busway baru menyesuaikan dengan tata ruang perkotaan.",
        "Terdapat stasiun pengisian daya listrik baterai umum di area parkir stasiun.",
        "Pelanggan dapat menukarkan poin keanggotaan tiket dengan suvenir resmi KAI.",
        "Uji coba operasional kereta layang terus dilakukan sebelum diresmikan.",
        "Kebijakan tarif integrasi berlaku jika penumpang berganti moda dalam tiga jam.",
        "Tinggi peron stasiun disesuaikan dengan tinggi pintu masuk gerbong kereta.",
        "Pemasangan jembatan penyeberangan menghubungkan stasiun MRT dengan pusat perbelanjaan.",
        "Kartu multi trip KRL dapat dibeli di loket stasiun commuter line.",
        "Pemerintah mengalokasikan anggaran khusus untuk pemeliharaan jalur rel kereta.",
        "Jumlah kunjungan pejabat negara ke lokasi IKN tercatat meningkat bulan ini.",
        "Transjakarta menyediakan area khusus bagi penumpang wanita di bagian depan bus.",
        "Rencana pembangunan stasiun KRL baru di kawasan permukiman sedang dievaluasi.",
        "Petugas keamanan melakukan pemeriksaan barang bawaan penumpang secara acak.",
        "Jadwal keberangkatan kereta api jarak jauh tertera pada tiket fisik penumpang.",
        "Fasilitas rak bagasi di atas tempat duduk gerbong KRL digunakan untuk tas kecil.",
        "Pemerintah mengeluarkan peta jalan pengembangan sistem logistik nasional.",
        "Stasiun BNI City melayani naik turun penumpang KRL Commuter Line.",
        "Lebar pintu masuk stasiun KRL disesuaikan dengan kapasitas volume komuter.",
        "Terdapat petunjuk arah evakuasi darurat di dinding lorong stasiun.",
        "Sistem pemantauan cuaca terhubung langsung dengan pusat kendali operasional kereta.",
        "Pembersihan rutin kaca jendela gerbong dilakukan setiap kereta masuk depo.",
        "Ketinggian jembatan layang disesuaikan agar aman dilewati bus tingkat.",
        "Kebijakan park and ride bertujuan memindahkan pengendara ke transportasi publik.",
        "Sosialisasi tata cara tap kartu dilakukan melalui poster informasi di pintu stasiun.",
        "Rencana perpanjangan rute KRL menuju kawasan industri sedang didiskusikan."
    ]
    
    # Kumpulkan data ke satu list
    dataset = []
    for t in positif:
        dataset.append((t, "Positif"))
    for t in negatif:
        dataset.append((t, "Negatif"))
    for t in netral:
        dataset.append((t, "Netral"))
        
    return dataset

def main():
    data = generate_data()
    filename = 'dataset_pelatihan.csv'
    
    with open(filename, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        # Menulis header kolom
        writer.writerow(['text_baku', 'label_sentimen'])
        # Menulis data
        writer.writerows(data)
        
    print(f"[SUCCESS] Berhasil membuat {len(data)} baris data latih di '{filename}'")

if __name__ == "__main__":
    main()
